### ISSUE TITLE
Error when running validate-ddf

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/ddf-validation#274]
Platform: windows 10
Node: v4.2.6
ddf-validation: 1.1.0

Reproduce:
1. run `validate-ddf -i` or `validate-ddf` on latest systema globalis (or any)

Result:
```
D:\github\open-numbers\ddf--gapminder--systema_globalis>validate-ddf
C:\Users\Jasper\AppData\Roaming\npm\node_modules\ddf-validation\lib\data\data-package.js:118
                (folderErr, ddfTransFileDescriptors = []) => {
                                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Jasper\AppData\Roaming\npm\node_modules\ddf-validation\cli.js:5:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Expected result:
datapackage.json is created or dataset is validated

**Comment by buchslava** [comment]
this ddf-validation is based on nodejs 6.9.1 (current LTS)?

can you update your nodejs? it will resolve this issue.

**Comment by jheeffer** [comment]
Yes, that helped : )
