### ISSUE TITLE
error in creation of ddfSchema for dummy dataset

### ISSUE THREAD

**Issue by semio** [Gapminder/ddf-validation#406]
dataset:  https://github.com/Gapminder/ddf--gapminder--dummy_companies

`validate-ddf -i` gives following error:

```
generating ddfSchema...
/usr/local/lib/node_modules/ddf-validation/lib/data/ddf-schema.js:75
        for (let row of dataset.dataHash[resource.path]) {
                                        ^

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at getDdfSchemaContent (/usr/local/lib/node_modules/ddf-validation/lib/data/ddf-schema.js:75:41)
    at ddfDataSet.load (/usr/local/lib/node_modules/ddf-validation/lib/data/ddf-schema.js:184:9)
    at async_1.parallel (/usr/local/lib/node_modules/ddf-validation/lib/ddf-definitions/ddf-data-set.js:61:17)
    at /usr/local/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:3838:9
    at /usr/local/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/usr/local/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:998:13)
    at /usr/local/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:906:16
    at /usr/local/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:3835:13
    at expectedClass.(anonymous function).getTranslationsData.translationsErr (/usr/local/lib/node_modules/ddf-validation/lib/ddf-definitions/ddf-data-set.js:40:116)
    at /usr/local/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:3838:9
```

**Comment by semio** [comment]
still got issue after update to 1.5.18:

```
generating ddfSchema...
/usr/local/lib/node_modules/ddf-validation/lib/data/ddf-schema.js:62
        for (let row of dataset.dataHash[resource.path]) {
                                        ^

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at getDdfSchemaContent (/usr/local/lib/node_modules/ddf-validation/lib/data/ddf-schema.js:62:41)
    at ddfDataSet.load (/usr/local/lib/node_modules/ddf-validation/lib/data/ddf-schema.js:207:9)
    at async_1.parallel (/usr/local/lib/node_modules/ddf-validation/lib/ddf-definitions/ddf-data-set.js:61:17)
    at /usr/local/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:3838:9
    at /usr/local/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/usr/local/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:996:13)
    at /usr/local/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:906:16
    at /usr/local/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:3835:13
    at expectedClass.(anonymous function).getTranslationsData.translationsErr (/usr/local/lib/node_modules/ddf-validation/lib/ddf-definitions/ddf-data-set.js:40:116)
    at /usr/local/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:3838:9
```
