### ISSUE TITLE
Validator crashing on this dataset

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/ddf-validation#549]
ddf-validation v1.19.0
node v8.15.0

clone dataset and branch from here
https://github.com/geoinfobyran/ddf--sodertornsmodellen/tree/access-and-year-3-sv

run validate-ddf
observe errors in the output

```
/Users/angie/.nvm/versions/node/v8.15.0/lib/node_modules/ddf-validation/lib/ddf-rules/entity-rules/unexisting-constraint-value.js:27
            const constrainedSchemaFields = relatedResourceSchema.schema.fields.filter(field => field.constraints && field.constraints.enum);
                                                                  ^

TypeError: Cannot read property 'schema' of undefined
    at dataPackageObject.fileDescriptors.filter.map (/Users/angie/.nvm/versions/node/v8.15.0/lib/node_modules/ddf-validation/lib/ddf-rules/entity-rules/unexisting-constraint-value.js:27:67)
    at Array.map (<anonymous>)
    at Object.rule (/Users/angie/.nvm/versions/node/v8.15.0/lib/node_modules/ddf-validation/lib/ddf-rules/entity-rules/unexisting-constraint-value.js:24:83)
    at getValidationSyncResultBySimpleRules (/Users/angie/.nvm/versions/node/v8.15.0/lib/node_modules/ddf-validation/lib/shared.js:17:57)
    at Object.exports.getSimpleRulesResult (/Users/angie/.nvm/versions/node/v8.15.0/lib/node_modules/ddf-validation/lib/shared.js:106:12)
    at Object.exports.validationProcess (/Users/angie/.nvm/versions/node/v8.15.0/lib/node_modules/ddf-validation/lib/shared.js:125:43)
    at ddfDataSet.load (/Users/angie/.nvm/versions/node/v8.15.0/lib/node_modules/ddf-validation/lib/index.js:179:22)
    at async_1.parallelLimit (/Users/angie/.nvm/versions/node/v8.15.0/lib/node_modules/ddf-validation/lib/ddf-definitions/ddf-data-set.js:85:17)
    at /Users/angie/.nvm/versions/node/v8.15.0/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:3838:9
    at /Users/angie/.nvm/versions/node/v8.15.0/lib/node_modules/ddf-validation/node_modules/async/dist/async.js:421:16
```

**Comment by angiehjort** [comment]
i retested everything 
✅ ddf-validation@1.19.3
